[package]
name = "nextclade"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
assert2 = { workspace = true }
auto_ops = { workspace = true }
base64 = { workspace = true }
bio = { workspace = true }
bio-types = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
clap_complete_fig = { workspace = true }
color-eyre = { workspace = true }
csv = { workspace = true }
ctor = { workspace = true }
derive_more = { workspace = true }
edit-distance = { workspace = true }
either = { workspace = true }
env_logger = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
gcollections = { workspace = true }
getrandom = { workspace = true }
indexmap = { workspace = true }
intervallum = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
maplit = { workspace = true }
multimap = { workspace = true }
num = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
optfield = { workspace = true }
ordered-float = { workspace = true }
owo-colors = { workspace = true }
pretty_assertions = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
rust_xlsxwriter = { workspace = true }
schemars = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_stacker = { workspace = true }
serde_yaml = { workspace = true }
strsim = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tinytemplate = { workspace = true }
traversal = { workspace = true }
urlencoding = { workspace = true }
validator = { workspace = true }
wasm-bindgen = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
atty = { workspace = true }
bzip2 = { workspace = true }
xz2 = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
criterion = { workspace = true }
rstest = { workspace = true }


[[bench]]
name = "bench_create_stripes"
harness = false

[[bench]]
name = "bench_seed_alignment"
harness = false
