[package]
name = "typescript-definitions"
version = "0.1.10"
description = "serde support for exporting Typescript definitions"
readme = "README.md"
authors = ["Tim Ryan <id@timryan.org>", "Sam Rijs <srijs@airpost.net>" , "Ian Castleden <ian.castleden@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/arabidopsis/typescript-definitions"
keywords =["typescript", "serde"]
categories = ["data-structures", "development-tools", "wasm" , "web-programming"]
edition = "2018"
exclude = ['scripts/*', 'templates/*' ]


[dependencies]
serde = "1.0.87"
typescript-definitions-derive = { version = "0.1.10",  path = "typescript-definitions-derive" }

[dev-dependencies]
serde = { version = "1.0.87", features = ["derive"] }
wasm-bindgen = "0.2.36"
quote = "0.6.11"
proc-macro2 = "0.4.27"
regex = "1.1.0"
serde_json = "1.0.38"
# insta = "0.6.2"
insta = { version="0.6" }
chrono = { version = "0.4", features = ["serde"] }
arrayvec = { version="0.4.10", features = ["serde-1"] }
# compiletest_rs = "*"


[features]
# default = ["type-guards"]
export-typescript = ["typescript-definitions-derive/export-typescript"]
test = ["typescript-definitions-derive/test"]
type-guards = ["typescript-definitions-derive/type-guards"]

[workspace]
# exclude = ["example"]

