[package]
name = "nextclade-cli"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
assert2 = { workspace = true }
clap = { workspace = true }
clap-markdown = { workspace = true }
clap_complete = { workspace = true }
clap_complete_fig = { workspace = true }
color-eyre = { workspace = true }
comfy-table = { workspace = true }
crossbeam = { workspace = true }
crossbeam-channel = { workspace = true }
ctor = { workspace = true }
dotenv = { workspace = true }
dotenv_codegen = { workspace = true }
eyre = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
nextclade = { path = "../nextclade" }
num_cpus = { workspace = true }
ordered-float = { workspace = true }
owo-colors = { workspace = true }
pretty_assertions = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
schemars = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tinytemplate = { workspace = true }
url = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
criterion = { workspace = true }
rstest = { workspace = true }
