[package]
name = "nextclade-web"
build = "src/build.rs"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
assert2 = { workspace = true }
chrono = { workspace = true }
console_error_panic_hook = { workspace = true }
eyre = { workspace = true }
getrandom = { workspace = true }
itertools = { workspace = true }
js-sys = { workspace = true }
log = { workspace = true }
maplit = { workspace = true }
nextclade = { path = "../nextclade" }
rust_xlsxwriter = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-logger = { workspace = true }
web-sys = { workspace = true }

[build-dependencies]
nextclade = { path = "../nextclade" }
schemars = { workspace = true }
eyre = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-simd", "--enable-nontrapping-float-to-int"]
