[package]
edition = "2021"
name = "bio_inline"
version = "1.3.1"

[dependencies]
bio-types = "=1.0.0"
bit-set = "=0.5.3"
bv = { version = "=0.11.1", features = ["serde"] }
bytecount = "=0.6.3"
fxhash = "=0.2.1"
lazy_static = "=1.4.0"
num = "=0.4.0"
num-integer = "0.1.45"
num-traits = "=0.2.15"
serde = { version = "=1.0.164", features = ["derive"] }
vec_map = { version = "=0.8.2", features = ["serde"] }

[features]
generic-simd = ["bytecount/generic-simd"]
runtime-dispatch-simd = ["bytecount/runtime-dispatch-simd"]
